name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: tuvidanueva.org
          username: tuvibizp
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 21098
          script: |
            cd ~/vidanueva
            git pull origin main
            yarn install --frozen-lockfile
            touch tmp/restart.txt
